/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaFinal;
import java.awt.Color;
import java.awt.Cursor;
import sm.jdrg.iu.Lienzo2Dimagen;

/**
 * Clase VentanaInterna. Ventana que contiene imagen o lienzo
 * @author jdrgj
 */
public class VentanaInterna extends VentanaInternaMultimedia {

        private final VentanaPrincipal ventanaPrin;

    /**
     * Creates new form VentanaInterna
     */

        public VentanaInterna(VentanaPrincipal vp) {
        this.ventanaPrin = vp;
        initComponents();
    }
    
        /**
        * Devuelve el lienzo imagen
        * @return LienzoImagen
        */
       public Lienzo2Dimagen getLienzo() {
        return lienzo2Dimagen1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo2Dimagen1 = new sm.jdrg.iu.Lienzo2Dimagen();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Practica11");

        javax.swing.GroupLayout lienzo2Dimagen1Layout = new javax.swing.GroupLayout(lienzo2Dimagen1);
        lienzo2Dimagen1.setLayout(lienzo2Dimagen1Layout);
        lienzo2Dimagen1Layout.setHorizontalGroup(
            lienzo2Dimagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );
        lienzo2Dimagen1Layout.setVerticalGroup(
            lienzo2Dimagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lienzo2Dimagen1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lienzo2Dimagen1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lienzoImagen1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoImagen1MouseDragged
    
    }//GEN-LAST:event_lienzoImagen1MouseDragged

    private void lienzoImagen1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoImagen1MouseExited
        
        
    }//GEN-LAST:event_lienzoImagen1MouseExited

    private void lienzoImagen1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoImagen1MouseMoved
       
    }//GEN-LAST:event_lienzoImagen1MouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sm.jdrg.iu.Lienzo2Dimagen lienzo2Dimagen1;
    // End of variables declaration//GEN-END:variables
}
